# Generated by Django 3.2.18 on 2023-05-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='category',
            field=models.CharField(choices=[('outer', '아우터'), ('top', '상의'), ('bottom', '하의'), ('cap', '모자'), ('accessories', '악세서리')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('Free', 'free')], max_length=15),
        ),
    ]
