# Generated by Django 3.2.18 on 2023-05-17 02:09

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommend',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='recommend',
            name='clothes_tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='RecommendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='')),
                ('recommend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.recommend')),
            ],
        ),
    ]
