# Generated by Django 3.2.18 on 2023-05-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20230517_1446'),
        ('clothes', '0007_remove_recommend_clothes_tags'),
    ]

    operations = [
    ]
