# Generated by Django 3.2.18 on 2023-05-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
        ('accounts', '0003_cart_purchaselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='carts',
            field=models.ManyToManyField(related_name='cart_users', through='accounts.Cart', to='clothes.Cloth'),
        ),
        migrations.AddField(
            model_name='user',
            name='purchase_logs',
            field=models.ManyToManyField(related_name='purchase_log_users', through='accounts.PurchaseLog', to='clothes.Cloth'),
        ),
    ]
